name: CustomMobDrops
api-version: 1.15
version: 0.1.0
author: shantek.io
main: io.shantek.custommobdrops

commands:
  shells:
    description: Main command for managing shulker shell drops.
    usage: /shells <min|max|debug|enabled> [value]
    aliases: [shulker]
    subcommands:
      min:
        description: Sets the minimum number of shulker shells dropped by shulkers.
        usage: /shells min <number>
      max:
        description: Sets the maximum number of shulker shells dropped by shulkers.
        usage: /shells max <number>
      debug:
        description: Enable/disable debug mode.
        usage: /shells debug <boolean>
      enabled:
        description: Enable/disable the custom drops.
        usage: /shells enabled <boolean>
