name: CustomMobDrops
api-version: 1.15
version: 0.1.0
author: shantek.io
main: io.shantek.CustomDrops

commands:
  customdrops:
    description: Main command for managing custom mob drops.
    usage: /customdrops ]
    aliases: [drops]
    subcommands:
      reload:
        description: Used to reload the plugin
        usage: /customdrops reload